apiVersion: v1
kind: Namespace
metadata:
  name: t-producer

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: t-producer-config
  namespace: t-producer
data:
  app_config.ini: |
    [app]
    redis_host = redis
    rabbitmq_host = rabbitmq
    minio_host = minio
    # Adicione outras configurações específicas do t-producer aqui

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: v-consumer-config
  namespace: t-producer
data:
  app_config.ini: |
    [app]
    redis_host = redis
    rabbitmq_host = rabbitmq
    minio_host = minio
    # Adicione outras configurações específicas do v-consumer aqui

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t-producer
  namespace: t-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t-producer
  template:
    metadata:
      labels:
        app: t-producer
    spec:
      containers:
        - name: t-producer
          image: willedy/t-producer:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: t-producer-config

---
apiVersion: v1
kind: Service
metadata:
  name: t-producer
  namespace: my-app
spec:
  selector:
    app: t-producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: v1
kind: Namespace
metadata:
  name: v-consumer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: v-consumer
  namespace: v-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v-consumer
  template:
    metadata:
      labels:
        app: v-consumer
    spec:
      containers:
        - name: v-consumer
          image: willedy/v-consumer:1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
      volumes:
        - name: config-volume
          configMap:
            name: v-consumer-config

---
apiVersion: v1
kind: Service
metadata:
  name: v-consumer
  namespace: v-consumer
spec:
  selector:
    app: v-consumer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080